// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	operations "github.com/ckpbin/core/restapi/product/operations"
	"github.com/labstack/echo/v4"
)

func Router(r *echo.Echo, service Service) {
	// setup all service routes after the authenticate middleware has been
	// initialized.
	r.GET("/products", operations.GetProductsEndpoint(service.GetProducts))

}
