// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/ckpbin/response"
	"github.com/labstack/echo/v4"

	operations "github.com/ckpbin/core/restapi/product/operations"
)

// Service is the interface that must be implemented in order to provide
// business logic for the Server service.
type Service interface {
	Healthy() bool
	GetProducts(ctx echo.Context, params *operations.GetProductsParams) *response.Response
}
