# docs https://swagger.io/docs/specification/2-0/
swagger: '2.0'
info:
  version: "0.0.1"
  title: Product Service
  description: Product to store information about product.
schemes:
  - http
  - https
host: localhost:8080
basePath: /
produces:
  - application/json
consumes:
  - application/json
paths:
  /products:
    get:
      operationId: getProducts
      parameters:
        - $ref: '#/parameters/limit'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/order_by'
        - $ref: '#/parameters/prev_page'
      responses:
        '200':
          description: Show all list products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'

parameters:
  limit:
    in: query
    name: limit
    type: integer
    minimum: 10
    maximum: 50
    default: 20
  offset:
    in: query
    name: offset
    type: integer
    minimum: 0
    default: 0
  order_by:
    in: query
    name: order_by
    type: array
    items:
      type: string
  prev_page:
    in: query
    name: prev_page
    type: array
    allowEmptyValue: true
    items:
      type: string

definitions:
  HttpError:
    type: object
    required:
      - status
      - type
      - title
    properties:
      detail:
        description: "More detailed, human-readable, optional explanation of the error"
        type: string
        example: User is lacking permission to access this resource
      status:
        description: HTTP status code returned for the error
        type: integer
        maximum: 599
        minimum: 100
        x-go-name: Code
        example: 403
      title:
        description: "Short, human-readable description of the error"
        type: string
        example: Forbidden
      type:
        description: "Type of error returned, should be used for client-side error handling"
        type: string
        example: generic

  HttpValidationError:
    allOf:
      - $ref: "#/definitions/HttpError"
    type: object
    required:
      - validationErrors
    properties:
      validationErrors:
        description: List of errors received while validating payload against schema
        type: array
        items:
          $ref: "#/definitions/HttpValidationErrorDetail"

  HttpValidationErrorDetail:
    type: object
    required:
      - key
      - in
      - error
    properties:
      error:
        description: Error describing field validation failure
        type: string
      in:
        description: Indicates how the invalid field was provided
        type: string
      key:
        description: Key of field failing validation
        type: string

  Product:
    type: object
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
