// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Auth service.",
    "title": "Auth Service",
    "version": "0.0.1"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "paths": {
    "/auth/register": {
      "post": {
        "operationId": "postRegister",
        "parameters": [
          {
            "name": "payload",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/PostRegisterPayload"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Show all list products",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "HttpError": {
      "type": "object",
      "required": [
        "status",
        "type",
        "title"
      ],
      "properties": {
        "detail": {
          "description": "More detailed, human-readable, optional explanation of the error",
          "type": "string",
          "example": "User is lacking permission to access this resource"
        },
        "status": {
          "description": "HTTP status code returned for the error",
          "type": "integer",
          "maximum": 599,
          "minimum": 100,
          "x-go-name": "Code",
          "example": 403
        },
        "title": {
          "description": "Short, human-readable description of the error",
          "type": "string",
          "example": "Forbidden"
        },
        "type": {
          "description": "Type of error returned, should be used for client-side error handling",
          "type": "string",
          "example": "generic"
        }
      }
    },
    "HttpValidationError": {
      "type": "object",
      "required": [
        "validationErrors"
      ],
      "allOf": [
        {
          "$ref": "#/definitions/HttpError"
        }
      ],
      "properties": {
        "validationErrors": {
          "description": "List of errors received while validating payload against schema",
          "type": "array",
          "items": {
            "$ref": "#/definitions/HttpValidationErrorDetail"
          }
        }
      }
    },
    "HttpValidationErrorDetail": {
      "type": "object",
      "required": [
        "key",
        "in",
        "error"
      ],
      "properties": {
        "error": {
          "description": "Error describing field validation failure",
          "type": "string"
        },
        "in": {
          "description": "Indicates how the invalid field was provided",
          "type": "string"
        },
        "key": {
          "description": "Key of field failing validation",
          "type": "string"
        }
      }
    },
    "PostRegisterPayload": {
      "type": "object",
      "required": [
        "username",
        "email",
        "password"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "password": {
          "type": "string",
          "format": "password"
        },
        "username": {
          "type": "string",
          "format": "uuid"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Auth service.",
    "title": "Auth Service",
    "version": "0.0.1"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "paths": {
    "/auth/register": {
      "post": {
        "operationId": "postRegister",
        "parameters": [
          {
            "name": "payload",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/PostRegisterPayload"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Show all list products",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "HttpError": {
      "type": "object",
      "required": [
        "status",
        "type",
        "title"
      ],
      "properties": {
        "detail": {
          "description": "More detailed, human-readable, optional explanation of the error",
          "type": "string",
          "example": "User is lacking permission to access this resource"
        },
        "status": {
          "description": "HTTP status code returned for the error",
          "type": "integer",
          "maximum": 599,
          "minimum": 100,
          "x-go-name": "Code",
          "example": 403
        },
        "title": {
          "description": "Short, human-readable description of the error",
          "type": "string",
          "example": "Forbidden"
        },
        "type": {
          "description": "Type of error returned, should be used for client-side error handling",
          "type": "string",
          "example": "generic"
        }
      }
    },
    "HttpValidationError": {
      "type": "object",
      "required": [
        "validationErrors"
      ],
      "allOf": [
        {
          "$ref": "#/definitions/HttpError"
        }
      ],
      "properties": {
        "validationErrors": {
          "description": "List of errors received while validating payload against schema",
          "type": "array",
          "items": {
            "$ref": "#/definitions/HttpValidationErrorDetail"
          }
        }
      }
    },
    "HttpValidationErrorDetail": {
      "type": "object",
      "required": [
        "key",
        "in",
        "error"
      ],
      "properties": {
        "error": {
          "description": "Error describing field validation failure",
          "type": "string"
        },
        "in": {
          "description": "Indicates how the invalid field was provided",
          "type": "string"
        },
        "key": {
          "description": "Key of field failing validation",
          "type": "string"
        }
      }
    },
    "PostRegisterPayload": {
      "type": "object",
      "required": [
        "username",
        "email",
        "password"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "password": {
          "type": "string",
          "format": "password"
        },
        "username": {
          "type": "string",
          "format": "uuid"
        }
      }
    }
  }
}`))
}
